---
- name: "Manage ldap entries"
  community.general.ldap_attrs:
    server_uri: "{{ ldap_auth['server_uri'] }}"
    bind_dn: "{{ ldap_auth['bind_dn'] }}"
    bind_pw: "{{ ldap_auth['bind_pw'] }}"
    validate_certs: "{{ ldap_auth['validate_certs'] | default(omit, true) }}"
    dn: "{{ item['dn'] }}"
    attributes: "{{ item['attributes'] | mandatory }}"
    state: "{{ item['state'] | default(omit) }}"
  loop: "{{ ldap_entries }}"
  loop_control:
    label: "{{ item['dn'] }} state={{ item['state'] | default('present') }}"
  when: item['attributes'] is defined
